### ISSUE TITLE
Read directly from a non-owned buffer in memory

### ISSUE THREAD

**Issue by teymour-aldridge** [jorgecarleitao/arrow2#1155]
At the moment (I think) `arrow2` can only read from something which implements the `Read` trait. The original `arrow` crate, however, can read IPC data which is already in memory directly (e.g. using https://docs.rs/arrow/latest/arrow/ipc/reader/fn.read_record_batch.html). Is there a way to do this in `arrow2`, or is it something which end-users should implement themselves?

**Comment by ritchie46** [comment]
You don't have to own the data. This snippet compiles:

```rust
use std::io::Cursor;

use arrow::error::Result;
use arrow::io::ipc::read;

fn main() -> Result<()> {
    /// Read from a borrowed buffer
    let mut buf: Cursor<&[u8]> = Cursor::new(&[]);

    // read the files' metadata. At this point, we can distribute the read whatever we like.
    let metadata = read::read_file_metadata(&mut buf)?;

    let schema = metadata.schema.clone();

    // Simplest way: use the reader, an iterator over batches.
    let reader = read::FileReader::new(buf, metadata, None, None);

    let chunks = reader.collect::<Result<Vec<_>>>()?;

    Ok(())
}
```

**Comment by ritchie46** [comment]
This snippet doesn't give ownership of the data.

And if you don't want to send the `buf` you could also pass a `&mut buf`.

**Comment by jorgecarleitao** [comment]
Note that arrow does not read from `&[u8]`, it memcopies the data. This implies that, in general, it performs two allocations - one from `Read` to `&[u8]`, and one from `&[u8]` to the arrays. One way to look at this is that a record batch is `&[u8]`, but an arrow array is owning the region, and thus `&[u8]` needs to be converted to multiple `Vec<u8>` (or equivalent in arrow-rs), one per array buffer.

In _theory_, we could perform a transmute from `&[u8]` to `&[T]` (e.g. `T=i32`) and define something like `PrimitiveArrayRef<'a>` that could have the same lifetime as `&'a[u8]`. However, this is unlikely to work - it would require the whole `&[u8]` to be allocated with a very specific alignment so that each of its buffers would align exactly to the alignment requirement of T.

Afaik we have an optimal setup here - we read directly from `Read` to arrow buffers without allocating an intermediary buffer. This is why @ritchie46 is suggesting using `Cursor` - we will need to read into the alignments of `T` anyways.
