### ISSUE TITLE
Add `extend` / `extend_unchecked` on builders/ mutablearrays 

### ISSUE THREAD

**Issue by ritchie46** [jorgecarleitao/arrow2#166]
What do you think of extending the `MutableArray` API's with those methods?

The [MutableBuffer](https://jorgecarleitao.github.io/arrow2/docs/arrow2/buffer/struct.MutableBuffer.html#method.extend_from_trusted_len_iter) already exposes this API. Often it's more user-friendly to work on the builders, as they maintain the overhead of the correct composite of arrays (a bitmap, an offset, a value-array, etc). With an `extend_(unchecked)` we can probably amortize allocation/bound checks.

**Comment by jorgecarleitao** [comment]
they currently implement `Extend` and `TryExtend` (some fail, so we keep it there). It makes sense to also have unchecked versions.

**Comment by VasanthakumarV** [comment]
@jorgecarleitao I would like to work on this issue,

Clarification:

- I see that `MutablePrimitiveArray` already implements [`extend_trusted_len_unchecked`](https://jorgecarleitao.github.io/arrow2/docs/arrow2/array/struct.MutablePrimitiveArray.html#method.extend_trusted_len_unchecked) and [`extend_trusted_len_values_unchecked`](https://jorgecarleitao.github.io/arrow2/docs/arrow2/array/struct.MutablePrimitiveArray.html#method.extend_trusted_len_values_unchecked), to close this issue we will have to implement these methods for other `MutableArray`s, is this correct?

**Comment by jorgecarleitao** [comment]
Exactly =)

In general, each mutable should have the following 4 functions:

1. `extend_trusted_len_values` and `extend_trusted_len_values_unchecked`, that extend by values (`i32`, `&str`, `&[u8]`)
2. `extend_trusted_len` and `extend_trusted_len_unchecked`, that extend by optional values (`Option<i32>`, `Option<&str>`, `Option<&[u8]>`)

To give some context on the why all these methods:

* We need `_unchecked` because `TrustedLen` in std is not `stable` and thus we have our own `TrustedLen`  that is not necessarily implemented for all possible iterators (even from std, such as `(0..100)`)
* We need them because Rust's Trait specialization is still not in `stable`, which means that we can't support both iterators and trustedlen on the same function name (`extend`).

Hope it clarifies the rational for them :)

**Comment by VasanthakumarV** [comment]
Thanks for the context @jorgecarleitao it really helps, I will make sure all the mutable implement the 4 functions.

**Comment by jorgecarleitao** [comment]
I think that this has been implemented, so closing it.
