### ISSUE TITLE
Consider bit operations for PrimitiveArray?

### ISSUE THREAD

**Issue by yjhmelody** [jorgecarleitao/arrow2#469]

**Comment by jorgecarleitao** [comment]
You mean `array1 ^ array2` type of operations?

**Comment by yjhmelody** [comment]
> You mean `array1 ^ array2` type of operations?

Right!

**Comment by jorgecarleitao** [comment]
Yeap, definitely in scope, and imo a fun exercise because it likely can be SIMDed!

**Comment by 1aguna** [comment]
Hello, I am new to the project and am interested in taking this on. Would the desired operations be

- `&` and
- `|`  or
- `^` xor

**Comment by jorgecarleitao** [comment]
Hey and welcome! 

Yap, those are the main ones. Check how we use the compute::arity::binary in other arithmetics for inspiration. 

Feel free to ping me if you need any help or have any questions 😊

**Comment by 1aguna** [comment]
I will check that out. Thanks!

**Comment by Dandandan** [comment]
I think bitwise not (`!` in Rust, `~` in some other languages) might be another important one.

A bit more "advanced" would be left and right shift.

**Comment by 1aguna** [comment]
@jorgecarleitao Do you have any tips for approaching SIMD ? From what I can tell, I should implement traits in `compute/aggregate/simd` for native(non-packed) and packed operations.

**Comment by jorgecarleitao** [comment]
You are on the right track 👍

For explicit SIMD, we have an abstraction for it (in `types/simd`) that allows both versions depending on the feature `simd`. However, like you wrote, we do need a trait to plug how each the specific operation (e.g. `^` or `!`) is represented in the SIMD space (e.g. `i8x64`).

I would first try to have a non-SIMD implementation (e.g. via `compute::arity::unary` and `compute::arity::binary`) and a benchmark, so that we have a baseline to work on top of (this could be one PR). It could be that rust auto-vectorizes and we do not need explicit SIMD.

Since this is not an aggregation, I would probably place it in a new module like `compute/logic` or something.

**Comment by jorgecarleitao** [comment]
Closed by #553
