### ISSUE TITLE
Performance: simd version for filter compute

### ISSUE THREAD

**Issue by sundy-li** [jorgecarleitao/arrow2#729]
ClickHouse Example:

https://github.com/ClickHouse/ClickHouse/blob/3d0e595579a641f30b46b3577a66059d87a15e0e/src/Columns/ColumnVector.cpp#L298-L420

**Comment by jorgecarleitao** [comment]
We already do something like that: our filter runs over the bitmap and computes the slices to be taken and "takes" slices of the array accordingly. For example, the filter `[true, true, false, false, true]` is mapped to `[[0,2], [4,1]]` and the final array is the concatenation of the slice `[0,2]` with the slice `[4,1]` of the array.

For multiple arrays, we persist `[[0,2], [4,1]]` (common across arrays) and applies the slicing to every array (in Rayon this can be parallelized).

**Comment by sundy-li** [comment]
Yes, so `filter` kernel can be merged into `take` kernel? Because the latter one covers the first.

**Comment by jorgecarleitao** [comment]
I haven't done it so because they have different invariants: filter is computed to "take non-overlapping, strictly index-increasing, slices of values", while take has no such invariant: the values can be taken out of order and the same index can be taken twice.

There are more optimizations possible in a filter than on a take.
