### ISSUE TITLE
format display binary arrays in hex instead of 01

### ISSUE THREAD

**Issue by houqp** [jorgecarleitao/arrow2#771]
This should address the last failing integration test for the datafusion arrow2 port, see https://github.com/houqp/arrow-datafusion/pull/18#issuecomment-1011929989.

The reasons for this suggestions:

1. hex encoding represents the same information, but is more compact and more idiomatic when it comes to binary data formatting
2. be consistent with pyarrow's behavior

Curious if there is any particular reason for switching from hex to binary encoding in arrow2?

Also cc @Igosuki

**Comment by Igosuki** [comment]
If the number of bits is not a multiple of 4 I guess. But then it could
simply detect that given the byte array length.

**Comment by jorgecarleitao** [comment]
This is an issue on the `io::print`, right?

The reason was that Rust's default Debug of a `&[u8]` is in decimal, i.e. I was trying to follow Rust's design choices, since those are usually what users expect.

With that said, representation seems a sufficiently difficult to problem to agree upon, since how an item is formatted depends a lot about who is looking at it, with which different communities have different assumptions of. Other examples include:

* datetime formats
* decimal separator (comma vs period)
* interval representation
* extension types (e.g. allow custom formatter when the type matches a custom extension)

Thus, could it be a way where we introduce a `WriteOption` for the print function that allows users to customize how items in an array are printed? E.g. `WriteOption::hexadecimal_binary` as our first one?

**Comment by houqp** [comment]
Got it. I think what you said makes sense if the consumer is another rust program. For high level compute engines, users would expect something closer to what databases do, I hex would be better IMO.

Considering it would only require copying 100+ lines of code to customize behavior, I think it would be better to just roll a custom display impl in datafusion for now until more people started to request for display customization. Not worth complicating the public API if this is something that's only needed by datafusion.
